frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"

contributors:
  - changed-files:
      - any-glob-to-any-file:
          - "public/contributors.json"

assets:
  - changed-files:
      - any-glob-to-any-file:
          - "public/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
